spring:
  data:
    redis:
      host: 192.168.31.100
      port: 30379
      password: lilishop
  datasource:
    url: jdbc:mysql://192.168.31.100:3306/lilishop?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: lilishop
lili:
  data:
    elasticsearch:
      cluster-nodes: 192.168.31.100:9200
      schema: http
    logstash:
      server: 127.0.0.1:4560
rocketmq:
  name-server: 192.168.31.100:9876
  producer:
    group: lili_group
    send-message-timeout: 30000