db_ip: 127.0.0.1
db_port: 3306
db_database: lilishop
db_username: root

spring:

  profiles:
    active: default

  # 文件大小上传配置
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  #jackson json解析
  jackson:
    time-zone: GMT+8
    serialization:
      #关闭jackson 对json做解析
      fail-on-empty-beans: false

  jpa:
    show-sql: true



# 忽略TOKEN 鉴权 的url
ignored:
  urls:
    # 买家端相关路径
    - /buyer/payment/cashier/**
    - /buyer/payment/cashierRefund/**
    - /buyer/other/pageData/**
    - /buyer/other/article/**
    - /buyer/goods/**
    - /buyer/store/**
    - /buyer/passport/connect/**
    - /buyer/members/**
    - /buyer/passport/member/**
    - /buyer/passport/member/refresh/**
    - /buyer/promotion/pintuan/**
    - /buyer/promotion/seckill/**
    - /buyer/promotion/pointsGoods/**
    - /buyer/promotion/coupon
    - /buyer/member/evaluation/*/goodsEvaluation
    - /buyer/member/evaluation/*/evaluationNumber
    - /buyer/other/appVersion/**
    - /buyer/broadcast/studio/**

    # 管理端相关路径
    - /manager/passport/user/login
    - /manager/passport/user/refresh/**
    - /manager/other/customWords

    # 店铺端相关路径
    - /store/passport/login/**
    - /store/passport/login/refresh/**

    # 通用资源路径
    - /common/common/slider/**
    - /common/common/sms/**
    - /common/common/logo
    - /common/common/site

    # 第三方集成路径
    - /weixin/**
    - /MP_verify_qSyvBPhDsPdxvOhC.txt

    # 开发调试工具路径
    - /swagger-ui.html
    - /swagger-ui/**
    - /v3/api-docs
    - /v3/api-docs/**

    # 静态资源路径
    - /static/**
    - /public/**
    - /resources/**
    - /META-INF/resources/**
    - /favicon.ico

    # 编辑器及源码路径
    - /editor-app/**
    - /source/**

    # 公共包
    - /common/**
    # IM
    - /im/**

# Mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    #缓存开启
    cache-enabled: true
    #日志
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 日志
logging:
  config: classpath:logback-spring.xml
  # 输出级别
  level:
    root: info
#    org.springframework: debug
  file:
    # 指定路径
    path: lili-logs

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui/index.html
  packages-to-scan: cn.lili.controller
  paths-to-match:
    - /buyer/**
    - /store/**
    - /manager/**

lili:
  system:
    isDemoSite: false
  statistics:
    # 在线人数统计 X 小时。这里设置48，即统计过去48小时每小时在线人数
    onlineMember: 48
    # 当前在线人数刷新时间间隔，单位秒，设置为600，则每10分钟刷新一次
    currentOnlineUpdate: 600

  # jwt 细节设定
  jwt-setting:
    # token过期时间（分钟）
    tokenExpireTime: 129600

  # 使用Spring @Cacheable注解失效时间
  cache:
    # 过期时间 单位秒 永久不过期设为-1
    timeout: 1500
  #多线程配置
  thread:
    corePoolSize: 5
    maxPoolSize: 50
    queueCapacity: 50
