spring:
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: lilishop
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/lilishop?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: lilishop
lili:
  data:
    elasticsearch:
      cluster-nodes: 127.0.0.1:9200
      schema: http
    logstash:
      server: 127.0.0.1:4560